version: '3'

services:
  db:
    image: mongo:6.0.6
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGODB_DATABASE=nest-pokedex
    volumes:
      - ./volumen_mongo_nestjs_pokedex:/data/db
